#--------------------------------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
#--------------------------------------------------------------------------------------

name: My-First-Basic-Action
env:
  APP_NAME  : "MyApp"
  PACK_NAME : "app-deploy-ver-${{ github.GITHUB_SHA }}"
on:
  push:
    branches: 
     - main
   
jobs:
  my_test_job_01:
    runs-on: ubuntu-latest

    steps:
    - name: Print hello Message in test
      run : echo "Hello world from job_01"
    
    - name: Execute few commands
      run : |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "App name: ${{ env.APP_NAME }}"
    
    - name: List current folder
      run : ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run : ls -la
              
  my_test_job_02:
    runs-on: ubuntu-latest
    needs: [my_test_job_01]
    env:
      VAR1 : "Variable 01"
      VAR2 : "Variable 02"
    
    steps:
    - name: Print hello Message in deploy
      run : echo "Hello world from job_02"
     
    - name: Printing Deployment packege
      run : echo "Deploy packege name is ${{ env.PACK_NAME }}"
      
    - name: Avaialble app aws
      run : aws --version
      
    - name: Available app zip
      run : zip --version

    - name: Show all vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Local Var1 = $LOCAL_VAR1"
        
      env:
        LOCAL_VAR1: "Local variable 01"
